[package]
name = "cubecli"
version = "0.1.0"
edition = "2021"
authors = ["Maya Hayden <mayahayden@protonmail.com>"]

[[bin]]
name = "cube"
path = "src/main.rs"

[dependencies]
cube = { path = "../cube" }
clap = {version="4.5", features=["derive"]}
image = "0.24"
